#!/usr/bin/env bash
# Build KenshiCoop.dll from Linux, driving the VC++ 2010 (v100) x64 toolchain
# through Wine. Companion to scripts/build_plugin.cmd, which needs Windows.
#
# The toolchain is extracted from the Windows SDK 7.1 ISO -- see
# scripts/linux/setup_toolchain.sh. Nothing is installed system-wide and no
# sudo is required; Wine comes from the Lutris runner directory.
#
#   Usage: scripts/linux/build_plugin.sh [Harness|Release|Debug]
set -euo pipefail

CONFIG="${1:-Harness}"
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TOOLCHAIN="${TOOLCHAIN:-$HOME/.local/share/kenshicoop-toolchain}"

source "$TOOLCHAIN/vcenv.sh"

OUT="$REPO/build/$CONFIG"
OBJ="$OUT/obj"
mkdir -p "$OBJ"

case "$CONFIG" in
  Release) DEFS="/DNDEBUG /DKENSHICOOP_EXPORTS"; OPT="/O2 /MD" ;;
  Harness) DEFS="/DNDEBUG /DKENSHICOOP_EXPORTS /DKENSHICOOP_HARNESS"; OPT="/O2 /MD" ;;
  Debug)   DEFS="/D_DEBUG /DKENSHICOOP_EXPORTS /DKENSHICOOP_HARNESS"; OPT="/Od /MDd" ;;
  *) echo "unknown config: $CONFIG (Harness|Release|Debug)" >&2; exit 2 ;;
esac
# CharacterSet=Unicode in the vcxproj: KenshiLib headers pass L"" literals to
# Win32 calls, so the W variants must be selected.
DEFS="$DEFS /D_WINDOWS /D_USRDLL /DWIN32_LEAN_AND_MEAN /DUNICODE /D_UNICODE"

# Stamp WHICH KenshiLib and ENet checkouts this DLL was compiled against, so the
# plugin can log them next to what actually serves it at runtime. Those are
# different things - the deps pin tracks a library RE_Kenshi ships separately -
# and until this existed nothing recorded the pair, so "what were they running?"
# was unanswerable after a crash report. The ENet pin matters the same way:
# both checkouts are gitignored, so the shas exist nowhere in the repo, and the
# vendored ENet (17 commits past v1.3.18) carries packet-parser hardening the
# release tarball lacks - see third_party/enet/README.md.
#
# -dirty is the HEALTHY state for both: patch_vendored_headers.sh mutates the
# deps and the two ENet patches mutate the ENet tree, by design.
#
# A generated header, not a /D string: the define would have to survive bash, then
# the Wine wrapper, then cl's own command-line parsing, and it did not.
DEPS_PIN="$(git -C "$REPO/third_party/KenshiLib_deps" describe --tags --always --dirty 2>/dev/null || echo unknown)"
ENET_PIN="$(git -C "$REPO/third_party/enet/enet" describe --always --dirty 2>/dev/null || echo unknown)"
# The honest build stamp: real time of THIS run plus the repo's own describe.
# Consumed only by BuildStamp.cpp, which compile_one recompiles unconditionally
# - a stamp read by an incrementally-skipped TU is exactly the lie the old
# __DATE__/__TIME__ banner told.
# --tags: the release tags are created by gh on the remote and arrive as
# LIGHTWEIGHT tags, which a bare describe ignores - the first stamped release
# shipped reading v0.50-15 while v0.55 existed. (Fetch tags for this to bite:
# git fetch --tags.)
BUILD_STAMP="$(date '+%Y-%m-%d %H:%M:%S') $(git -C "$REPO" describe --tags --always --dirty 2>/dev/null || echo unknown)"
mkdir -p "$REPO/build/generated"
printf '// Generated by build_plugin.sh - do not edit, do not commit.\n#define KENSHICOOP_DEPS_PIN "%s"\n#define KENSHICOOP_ENET_PIN "%s"\n#define KENSHICOOP_BUILD_STAMP "%s"\n' \
    "$DEPS_PIN" "$ENET_PIN" "$BUILD_STAMP" > "$REPO/build/generated/DepsPin.h"
DEFS="$DEFS /DKENSHICOOP_HAVE_DEPS_PIN"

# Whole program optimization, read from the vcxproj rather than assumed.
#
# THIS IS LOAD-BEARING, not an optimization preference. It lives in a
# Label="Configuration" <PropertyGroup>, not in the <ItemDefinitionGroup> where
# every other compiler and linker setting sits, and this script read only the
# latter - so every DLL it ever produced was built WITHOUT /GL while the project
# demanded it.
#
# What that costs: KenshiLib's member-function stubs get emitted as ordinary
# local functions, so `&GameWorld::_NV_mainLoop_GPUSensitiveStuff` resolves to an
# address inside KenshiCoop.dll and KenshiLib::GetRealAddress asserts on it
# before the plugin finishes loading. The game shows an assertion box and then
# crashes. The assertion text says "try enabling whole program optimization" and
# means exactly that.
LTCG=""
if [ "$(python3 "$REPO/scripts/linux/vcxproj_sources.py" \
          "$REPO/src/plugin/KenshiCoop.vcxproj" "$CONFIG" x64 --wpo)" = "1" ]; then
    OPT="$OPT /GL"
    LTCG="/LTCG"
fi

export INCLUDE="$(vc_include "$REPO");$(winpath "$REPO/build/generated")"
export LIB="$(vc_lib "$REPO")"

# The vcxproj is authoritative for the source list on both build paths, including
# its per-configuration <ExcludedFromBuild> markers -- Release must not contain
# the scenario harness or the EngineProbe detours. ENet's unix.c is absent from
# the project entirely (Windows socket backend only).
mapfile -t SOURCES < <(
  python3 "$REPO/scripts/linux/vcxproj_sources.py" \
    "$REPO/src/plugin/KenshiCoop.vcxproj" "$CONFIG" x64
)
[ "${#SOURCES[@]}" -gt 0 ] || { echo "no sources for $CONFIG" >&2; exit 1; }

# Force a full rebuild when the FLAGS change, not just when sources do.
#
# The incremental check below compares timestamps only, so a flag change leaves
# every existing object in place and the link silently mixes objects built two
# different ways - which for /GL means mixing IL objects with native ones. The
# flag set is therefore part of the build's identity and is stamped alongside the
# objects.
STAMP="$OUT/.buildflags"
STAMP_NOW="OPT=$OPT DEFS=$DEFS LTCG=$LTCG"
if [ ! -f "$STAMP" ] || [ "$(cat "$STAMP")" != "$STAMP_NOW" ]; then
    if [ -f "$STAMP" ]; then
        echo "=== build flags changed since the last run - full rebuild ==="
    fi
    rm -rf "$OBJ"; mkdir -p "$OBJ"
fi

echo "=== KenshiCoop.dll ($CONFIG|x64, v100 via Wine) - ${#SOURCES[@]} translation units ==="

obj_for() {
  # Flatten the path into the object name, dropping the leading ../.. of the
  # vendored ENet sources so nothing lands as a dotfile.
  echo "$OBJ/$(echo "${1%.*}" | tr '/' '_' | sed 's/^[._]*//').obj"
}

# Recompile only when the source is newer than its object, unless KC_REBUILD=1.
#
# Deliberately a timestamp check on the .cpp alone and NOT a header dependency
# scan: this codebase's headers are load-bearing (Replicator.h is included by
# nearly everything and changes constantly), so a naive source-only check would
# happily skip a TU that a header change had invalidated. Touching any header
# therefore forces a full rebuild - correctness first, and the win is still real
# for the common case of editing one .cpp.
#
# The scan covers EVERYTHING on the include path - src, vc10_compat, the
# KenshiLib deps (boost included) and ENet - because the narrow version of this
# check (src + vc10_compat, 34 headers of the 11,576 handed to cl.exe) made
# every KenshiLib or ENet header change a silent stale-object generator:
# patch_vendored_headers.sh rewrites 164 vendored headers and rebuilt NOTHING
# unless KC_REBUILD=1 was remembered by hand. One find pass, not one per TU -
# stat'ing ~12k files once is cheap, forty times that is not. build/ is
# deliberately excluded: DepsPin.h is regenerated on every run and would force
# a full rebuild every time.
NEWEST_HDR_FILE="$(find "$REPO/src" "$REPO/third_party/vc10_compat" \
        "$REPO/third_party/KenshiLib_deps/KenshiLib/Include" \
        "$REPO/third_party/KenshiLib_deps/boost_1_60_0" \
        "$REPO/third_party/enet/enet/include" \
        \( -name '*.h' -o -name '*.hpp' \) -printf '%T@ %p\n' 2>/dev/null |
    sort -n | tail -1 | cut -d' ' -f2-)"

compile_one() {
  local src="$1"
  local abs="$REPO/src/plugin/$src"
  local obj="$(obj_for "$src")"

  # BuildStamp.cpp is NEVER skipped: its whole job is to carry the
  # KENSHICOOP_BUILD_STAMP of THIS run (DepsPin.h regenerates every run but is
  # deliberately outside the header-freshness scan), so taking the incremental
  # skip here would freeze the stamp exactly the way __DATE__ froze the banner.
  case "$src" in *BuildStamp.cpp) ;; *)
  if [ -z "${KC_REBUILD:-}" ] && [ -f "$obj" ] && [ "$obj" -nt "$abs" ] &&
     [ -n "$NEWEST_HDR_FILE" ] && [ "$obj" -nt "$NEWEST_HDR_FILE" ]; then
    return 0   # object is newer than the source AND every header on the path
  fi
  ;; esac
  # Delete first. The success test below is "does the object exist", and without
  # this a compile that FAILS leaves the previous run's object sitting there and
  # passes it -- so the link succeeds against stale code and verify.sh reports a
  # green gate for a plugin that does not contain the change being tested. The
  # grep that strips cl.exe's filename echo also swallows its exit status, which
  # is why existence is the test at all.
  rm -f "$obj"
  # /EHsc: the plugin mixes C++ objects with __try frames; /W3 matches Level3.
  vcl /nologo /c /EHsc /W3 /Gy /Oi $OPT $DEFS \
      /Fo"$(winpath "$obj")" "$(winpath "$abs")" 2>&1 |
    grep -vE '^[A-Za-z0-9_./\\-]+\.(cpp|c)$' || true
  [ -f "$obj" ] || { echo "FAILED: $src" >&2; return 1; }
}
export -f compile_one obj_for winpath vcl
export REPO OBJ OPT DEFS VC WINE_BIN NEWEST_HDR_FILE

printf '%s\n' "${SOURCES[@]}" |
  xargs -P "$(nproc)" -I{} bash -c 'compile_one "$@"' _ {}

# Link exactly what this run produced. Globbing the object directory instead
# would sweep up stale objects from an earlier layout and hand the linker two
# definitions of everything (LNK2005).
OBJS=()
for src in "${SOURCES[@]}"; do
  obj="$(obj_for "$src")"
  [ -f "$obj" ] || { echo "missing object for $src -- compile failed" >&2; exit 1; }
  OBJS+=("$(winpath "$obj")")
done

echo "=== linking ${#OBJS[@]} objects ==="
vclink /nologo /DLL /SUBSYSTEM:WINDOWS /OPT:REF /OPT:ICF /DEBUG $LTCG \
  /OUT:"$(winpath "$OUT/KenshiCoop.dll")" \
  /PDB:"$(winpath "$OUT/KenshiCoop.pdb")" \
  /MAP:"$(winpath "$OUT/KenshiCoop.map")" \
  "${OBJS[@]}" \
  kenshilib.lib OgreMain_x64.lib MyGUIEngine_x64.lib ws2_32.lib winmm.lib \
  user32.lib kernel32.lib advapi32.lib shell32.lib ole32.lib

# Loadability check: is this DLL one the game will actually accept?
#
# The build succeeding proves nothing about that. A plugin compiled without /GL
# links perfectly and then dies at startup on a KenshiLib assertion, because
# `&GameWorld::_NV_mainLoop_GPUSensitiveStuff` resolved to a LOCAL definition in
# our own module instead of to KenshiLib's stub. Five releases shipped that way.
#
# The map answers it without launching anything: the symbol must appear as
# __imp_ (an import from KenshiLib.dll) and must NOT appear as a definition.
if [ -f "$OUT/KenshiCoop.map" ]; then
    HOOKSYM='_NV_mainLoop_GPUSensitiveStuff'
    if ! grep -q "__imp_.*$HOOKSYM" "$OUT/KenshiCoop.map"; then
        echo "FATAL: $HOOKSYM is not imported from KenshiLib in this build." >&2
        echo "       The plugin would assert in KenshiLib::GetRealAddress at startup." >&2
        echo "       Almost always: whole program optimization (/GL + /LTCG) is missing." >&2
        rm -f "$OUT/KenshiCoop.dll"
        exit 1
    fi
    if grep -qE "^ [0-9]{4}:[0-9A-Fa-f]{8} +\?$HOOKSYM@" "$OUT/KenshiCoop.map"; then
        echo "FATAL: $HOOKSYM has a LOCAL definition in this build - see above." >&2
        rm -f "$OUT/KenshiCoop.dll"
        exit 1
    fi
    echo "loadable: $HOOKSYM resolves through KenshiLib's import"
fi

# ...and that the deps stamp actually reached the binary. It silently did not once
# already (a C++17 __has_include guard on a C++03 compiler evaluates to 0), and the
# build reported success either way.
# grep the binary DIRECTLY (-a), with no pipe. `strings ... | grep -q` looks
# equivalent and is not: grep -q exits the instant it matches, strings takes
# SIGPIPE, and under `set -o pipefail` the pipeline then reports failure even
# though the match SUCCEEDED. That false alarm cost a rebuild cycle to chase.
if ! LC_ALL=C grep -qaF "$DEPS_PIN" "$OUT/KenshiCoop.dll"; then
    echo "FATAL: the deps pin '$DEPS_PIN' is not in the built DLL - the stamp was" >&2
    echo "       compiled out and the plugin will log 'unstamped'." >&2
    rm -f "$OUT/KenshiCoop.dll"
    exit 1
fi
echo "stamped: built against KenshiLib $DEPS_PIN"

if ! LC_ALL=C grep -qaF "$ENET_PIN" "$OUT/KenshiCoop.dll"; then
    echo "FATAL: the ENet pin '$ENET_PIN' is not in the built DLL - the stamp was" >&2
    echo "       compiled out and the plugin will log 'unstamped'." >&2
    rm -f "$OUT/KenshiCoop.dll"
    exit 1
fi
echo "stamped: vendored ENet $ENET_PIN"

# Only stamp AFTER a successful link, so an interrupted or failed build does not
# convince the next run that its objects match these flags.
printf '%s' "$STAMP_NOW" > "$STAMP"

ls -la "$OUT/KenshiCoop.dll"
sha256sum "$OUT/KenshiCoop.dll"
